using System.Text.Json.Serialization;

namespace StarTradersUi.Api;

[JsonConverter(typeof(JsonStringEnumConverter))]
public enum FactionTraitSymbol
{
    [JsonStringEnumMemberName("BUREAUCRATIC")]
    Bureucratic,
    [JsonStringEnumMemberName("SECRETIVE")]
    Secretive,
    [JsonStringEnumMemberName("CAPITALISTIC")]
    Capitalistic,
    [JsonStringEnumMemberName("INDUSTRIOUS")]
    Industrious,
    [JsonStringEnumMemberName("PEACEFUL")]
    Peaceful,
    [JsonStringEnumMemberName("DISTRUSTFUL")]
    Distrustful,
    [JsonStringEnumMemberName("WELCOMING")]
    Welcoming,
    [JsonStringEnumMemberName("SMUGGLERS")]
    Smugglers,
    [JsonStringEnumMemberName("SCAVENGERS")]
    Scavengers,
    [JsonStringEnumMemberName("REBELLIOUS")]
    Rebellious,
    [JsonStringEnumMemberName("EXILES")]
    Exiles,
    [JsonStringEnumMemberName("PIRATES")]
    Pirates,
    [JsonStringEnumMemberName("RAIDERS")]
    Raiders,
    [JsonStringEnumMemberName("CLAN")]
    Clan,
    [JsonStringEnumMemberName("GUILD")]
    Guild,
    [JsonStringEnumMemberName("DOMINION")]
    Dominion,
    [JsonStringEnumMemberName("FRINGE")]
    Fringe,
    [JsonStringEnumMemberName("FORSAKEN")]
    Forsaken,
    [JsonStringEnumMemberName("ISOLATED")]
    Isolated,
    [JsonStringEnumMemberName("LOCALIZED")]
    Localized,
    [JsonStringEnumMemberName("ESTABLISHED")]
    Established,
    [JsonStringEnumMemberName("NOTABLE")]
    Notable,
    [JsonStringEnumMemberName("DOMINANT")]
    Dominant,
    [JsonStringEnumMemberName("INESCAPABLE")]
    INESCAPABLE,
    [JsonStringEnumMemberName("INNOVATIVE")]
    Innovative,
    [JsonStringEnumMemberName("BOLD")]
    Bold,
    [JsonStringEnumMemberName("VISIONARY")]
    Visionary,
    [JsonStringEnumMemberName("CURIOUS")]
    Curious,
    [JsonStringEnumMemberName("DARING")]
    Daring,
    [JsonStringEnumMemberName("EXPLORATORY")]
    Exploratory,
    [JsonStringEnumMemberName("RESOURCEFUL")]
    Resourceful,
    [JsonStringEnumMemberName("FLEXIBLE")]
    Flexible,
    [JsonStringEnumMemberName("COOPERATIVE")]
    Cooperative,
    [JsonStringEnumMemberName("UNITED")]
    United,
    [JsonStringEnumMemberName("STRATEGIC")]
    Strategic,
    [JsonStringEnumMemberName("INTELLIGENT")]
    Intelligent,
    [JsonStringEnumMemberName("RESEARCH_FOCUSED")]
    ResearchFocused,
    [JsonStringEnumMemberName("COLLABORATIVE")]
    Collaborative,
    [JsonStringEnumMemberName("PROGRESSIVE")]
    Progressive,
    [JsonStringEnumMemberName("MILITARISTIC")]
    Militaristic,
    [JsonStringEnumMemberName("TECHNOLOGICALLY_ADVANCED")]
    TechnologicallyAdvanced,
    [JsonStringEnumMemberName("AGGRESSIVE")]
    Aggressive,
    [JsonStringEnumMemberName("IMPERIALISTIC")]
    Imperialistic,
    [JsonStringEnumMemberName("TREASURE_HUNTERS")]
    TreasureHunters,
    [JsonStringEnumMemberName("DEXTEROUS")]
    Dexterous,
    [JsonStringEnumMemberName("UNPREDICTABLE")]
    Unpredictable,
    [JsonStringEnumMemberName("BRUTAL")]
    Brutal,
    [JsonStringEnumMemberName("FLEETING")]
    Fleeting,
    [JsonStringEnumMemberName("ADAPTABLE")]
    Adaptable,
    [JsonStringEnumMemberName("SELF_SUFFICIENT")]
    Self_Sufficient,
    [JsonStringEnumMemberName("DEFENSIVE")]
    Defensive,
    [JsonStringEnumMemberName("PROUD")]
    Proud,
    [JsonStringEnumMemberName("DIVERSE")]
    Diverse,
    [JsonStringEnumMemberName("INDEPENDENT")]
    Independent,
    [JsonStringEnumMemberName("SELF_INTERESTED")]
    SelfInterested,
    [JsonStringEnumMemberName("FRAGMENTED")]
    Fragmented,
    [JsonStringEnumMemberName("COMMERCIAL")]
    Commercial,
    [JsonStringEnumMemberName("FREE_MARKETS")]
    FreeMarkets,
    [JsonStringEnumMemberName("ENTREPRENEURIAL")]
    Entrepreneurial,
}